In [27]:
import pandas as pd
missing_value=["?"]
cars = pd.read_csv("cars_price.csv",na_values=missing_value)
cars.head(5)

symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std   
1          3                NaN  alfa-romero       gas        std   
2          1                NaN  alfa-romero       gas        std   
3          2              164.0         audi       gas        std   
4          2              164.0         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0      111.0   
1          130         mpfi  3.47    2.68               9.0      111.0   
2          152         mpfi  2.68    3.47               9.0      154.0   
3          109         mpfi  3.19    3.40              10.0      102.0   
4          136         mpfi  3.19    3.40               8.0      115.0   

   peak-rpm city-mpg  highway-mpg    price  
0    5000.0       21           27  13495.0  
1    5000.0       21           27  16500.0  
2    5000.0       19           26  16500.0  
3    5500.0       24           30  13950.0  
4    5500.0       18           22  17450.0  

[5 rows x 26 columns]

In [29]:
cars=cars.drop(columns=['symboling','normalized-losses','aspiration','engine-location','engine-type'])

In [30]:
cars.isnull().sum()

make                 0
fuel-type            0
num-of-doors         2
body-style           0
drive-wheels         0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [32]:
cars=cars.dropna()

In [33]:
cars.isnull().sum()

make                 0
fuel-type            0
num-of-doors         0
body-style           0
drive-wheels         0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [37]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
cars['make']= label_encoder.fit_transform(cars['make'])
cars['make'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [39]:
cars['fuel-system']= label_encoder.fit_transform(cars['fuel-system'])
cars['fuel-system'].unique()

array([4, 1, 3, 0, 6, 2, 5])

In [40]:
cars['num-of-cylinders']= label_encoder.fit_transform(cars['num-of-cylinders'])
cars['num-of-cylinders'].unique()

array([2, 3, 1, 4, 5, 0])

In [41]:
cars['drive-wheels']= label_encoder.fit_transform(cars['drive-wheels'])
cars['drive-wheels'].unique()

array([2, 1, 0])

In [42]:
cars['body-style']= label_encoder.fit_transform(cars['body-style'])
cars['body-style'].unique()

array([0, 2, 3, 4, 1])

In [43]:
cars['num-of-doors']= label_encoder.fit_transform(cars['num-of-doors'])
cars['num-of-doors'].unique()

array([1, 0])

In [45]:
cars['fuel-type']= label_encoder.fit_transform(cars['fuel-type'])
cars['fuel-type'].unique()

array([1, 0])

In [46]:
cars.head(5)

make  fuel-type  num-of-doors  body-style  drive-wheels  wheel-base  \
0     0          1             1           0             2        88.6   
1     0          1             1           0             2        88.6   
2     0          1             1           2             2        94.5   
3     1          1             0           3             1        99.8   
4     1          1             0           3             0        99.4   

   length  width  height  curb-weight  ...  engine-size  fuel-system  bore  \
0   168.8   64.1    48.8         2548  ...          130            4  3.47   
1   168.8   64.1    48.8         2548  ...          130            4  3.47   
2   171.2   65.5    52.4         2823  ...          152            4  2.68   
3   176.6   66.2    54.3         2337  ...          109            4  3.19   
4   176.6   66.4    54.3         2824  ...          136            4  3.19   

   stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
0    2.68                9.0       111.0    5000.0        21           27   
1    2.68                9.0       111.0    5000.0        21           27   
2    3.47                9.0       154.0    5000.0        19           26   
3    3.40               10.0       102.0    5500.0        24           30   
4    3.40                8.0       115.0    5500.0        18           22   

     price  
0  13495.0  
1  16500.0  
2  16500.0  
3  13950.0  
4  17450.0  

[5 rows x 21 columns]

In [48]:
X = cars.drop(columns = 'price') 
y = cars['price'] 

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [50]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression(normalize=True)
regressor.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,


LinearRegression(normalize=True)

In [53]:
import numpy as np
y_pred = regressor.predict(X_test)
y_pred = np.round(y_pred)

In [54]:
final_model = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
final_model.head(5)

Actual  Predicted
120   6229.0     5334.0
146   7463.0     8432.0
48   35550.0    28646.0
135  15510.0    13465.0
170  11199.0    13661.0

In [55]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R squared value :', metrics.r2_score(y_test, y_pred))

Mean Absolute Error: 2294.6666666666665
Mean Squared Error: 10011541.17948718
Root Mean Squared Error: 3164.101954660624
R squared value : 0.8260515551986896
